### Benutzer registrieren
POST http://localhost:8080/api/users/register
Content-Type: application/json


{
"accessRights": "svf_commander",
"birthday": "1955-01-01T00:00:00.000Z",
"debts": "0.00",
"email": "admin@admin.de",
"gotRejected": false,
"gotSuit": false,
"isInjured": false,
"isInjuredType": null,
"isInjuredUntil": "1955-01-01T00:00:00.000Z",
"jerseyNumber": 0,
"name": "admin",
"password": "$2b$10$lwcn3ekOdFhFDVfFNcu8mOvwxpv7TauYODixuT8bGmss8x/dXawHW",
"position": "",
"role": "[\"Admin\"]",
"surname": "admin",
"userImage": {
"bgColor": "--blue-primary",
"bgImage": null,
"initials": "aa"
},
"userIsActivated": true,
"username": "admin",
"watchedTutorial": true
}

### Benutzer anmelden
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "username": "player1",
  "password": "1234"
}

### Passwort zurücksetzen anfordern
POST http://localhost:8080/api/users/forgot-password
Content-Type: application/json

{
  "email": "dennisghaas@gmail.com"
}

### Alle Benutzer anzeigen
GET http://localhost:8080/api/users
Content-Type: application/json

### Finde Nutzer nach ID
GET http://localhost:8080/api/users/2

### Alle Benutzer löschen
DELETE http://localhost:8080/api/users/delete-all

### Nutzer mit bestimmter ID löschen
DELETE http://localhost:8080/api/users/9

### Termin erstellen
POST http://localhost:8080/api/events/create
Content-Type: application/json

{
"author": "admin",
"eventDescription": {
"endAt": "13:07",
"title": "Heimspiel",
"meetAt": "10:00",
"beginAt": "11:00",
"subtitle": "Stellingen 2.",
"description": "",
"deadlineToStart": "2024-10-31T17:07:00.000Z"
},
"eventType": "Spiel",
"eventDate": "2024-11-03T00:00:00.000Z",
"venue": "Heimspiel",
"venueStreet": "Lawaetzstraße 8",
"venuePostalCode": "22844 Norderstedt",
"standingOrderID": null,
"showInDashboard": false,
"linkExtern": "https://www.fussball.de/spiel/friedrichsgabe-2-stellingen-2/-/spiel/02PUL024NK000000VS5489B4VVTKJJ35#!/",
"playerWithNoAccess": [],
"voteQuestion": "",
"voteOptions": [
{
"text": "",
"index": 0
},
{
"text": "",
"index": 1
}
],
"voteMultipleSelection": false
}

### Neuen Dauerauftrag erstellen
POST http://localhost:8080/api/standing-orders
Content-Type: application/json

{
  "standingOrderID": 1,
  "eventIDs": [1, 2, 3, 4, 5, 6]
}

### Dauerauftrag nach ID löschen
DELETE http://localhost:8080/api/standing-orders/1

### Alle Daueraufträge anzeigen
GET http://localhost:8080/api/standing-orders


### Alle Termine abrufen
GET http://localhost:8080/api/events

### Bestimmten Termin abrufen
GET http://localhost:8080/api/events/5

### Bestimmten Termin löschen
DELETE http://localhost:8080/api/events/1

### Alle Termine löschen
DELETE http://localhost:8080/api/events/delete-all

### Ändere die Daten eines bestimmten Users
PUT http://localhost:8080/api/users/2
Content-Type: application/json

{
"id": 2,
"accessRights": "svf_private",
"birthday": "1997-07-05T00:00:00.000Z",
"debts": 0,
"email": "dennisghaas@gmail.com",
"gotRejected": false,
"gotSuit": true,
"isInjured": false,
"isInjuredType": null,
"isInjuredUntil": "1955-01-01T00:00:00.000Z",
"jerseyNumber": 23,
"name": "Dennis",
"password": "$2b$10$6IhjzhoLW5881WnIcJeif.1HTAQtj2WPYGEg7U.VUXmXS.fBJL/Di",
"position": "Sechser",
"role": "[\"Spieler\",\"Mannschaftsrat\"]",
"surname": "Haas",
"userImage": {
"initials": "DH",
"bgColor": "--blue-primary"
},
"userIsActivated": true,
"username": "dennis"
}

### Event Response
POST http://localhost:8080/api/event-responses/respond
Content-Type: application/json

{
    "userId": 1,
    "eventId": 1,
    "response": "accept"
}

### Übersicht der Event-Reaktionen
GET http://localhost:8080/api/event-responses/overview/2
Content-Type: application/json

### Lösche jede Reaktion auf jedes Event
DELETE http://localhost:8080/api/event-responses